### ISSUE TITLE
Small in-book pictures instead of normal in iBooks

### ISSUE THREAD

**Issue by pasadena076** [readest/readest#1340]
## Bug Description

**Images/ illustrations in book is too small and not directly clickable**

![Image](https://github.com/user-attachments/assets/5cbce4c0-f7ce-4b86-8b88-1efe810e0274)

**In other reader (iBooks) same book looks normally**

![Image](https://github.com/user-attachments/assets/bbe27d17-2dde-4bb6-a309-c99277d9292f)

## Technical inputs
Operating System: MacOS Sequoia 15.5
Readest Version: Version 0.9.52 (0.9.52)

**Comment by chrox** [comment]
Could you share the link of the epub file?

**Comment by pasadena076** [comment]
> Could you share the link of the epub file?

Sure, [LINK](https://1drv.ms/u/c/078128b66411354c/EfysiYmZO75Pp1pvL1IsVbIB_IgDkzsUtUKRAhyvq1LnWg?e=ttAFak)

**Comment by pasadena076** [comment]
So what should i do with this info?

**Comment by chrox** [comment]
> So what should i do with this info?

It indicates this issue is fixed. And it's instantly available in the online version: https://web.readest.com, and for the apps it will be available in the next release.

**Comment by pasadena076** [comment]
> > So what should i do with this info?
> 
> It indicates this issue is fixed. And it's instantly available in the online version: https://web.readest.com, and for the apps it will be available in the next release.

Sounds perfect, thanks! Have a great day

**Comment by ahobsonsayers** [comment]
This doesn't seem to have fixed the issue. Some images appear the proper size, while others are wrong and are still very small. I am using the latest release that contains what was thought to be the fix. 

Here is a screenshot 

![Screenshot_20250611-021429_Readest.png](https://github.com/user-attachments/assets/28f086eb-5adb-4f79-a498-f44c3493c10c)

**Comment by chrox** [comment]
Please import the book with the Readest online version https://web.readest.com which has the latest fix for this. If it still has the problem, please upload the epub file.

**Comment by ahobsonsayers** [comment]
I tried using the web version as well, and it is the same issue. Regardless, the app version I am using has the release note that says this is fixed, so i'd expect that the behaviour would be the same.

I can't upload the epub as it is a book I purchased, and I think this would count as distribution of copyrighted material.

I am reading Hyperbole and a Half by Allie Brosh if that helps.

**Comment by chrox** [comment]
It’s possible that the issue is only partially fixed—some EPUB books include nonstandard or complex CSS that can still cause rendering problems, even if the core bug was addressed. We’ll take a closer look at how Hyperbole and a Half is styled. That could help us improve compatibility further.

**Comment by chrox** [comment]
![Image](https://github.com/user-attachments/assets/94c9d7b9-ecbf-4caf-8aaa-4bc8ea4b805c)
EPUB version.

![Image](https://github.com/user-attachments/assets/7d738eab-5170-4f61-970b-87627c1aecd8)
MOBI version.

I tried both the epub version and the mobi version with the Readest Web. It seems the images are rendered correct.

**Comment by chrox** [comment]
> This doesn't seem to have fixed the issue. Some images appear the proper size, while others are wrong and are still very small. I am using the latest release that contains what was thought to be the fix.

Could you share the screenshot of the 'About Readest'? There is also possibility that some old browsers may not render the image with proper size.

**Comment by ahobsonsayers** [comment]
Oh this is very interesting you don't see this!

Here is a screenshot from my About Readest on the web. I also tried with Chrome as well and got the same issue.

I wonder if this is because I am on mobile. I can try on my laptop tonight 

![Screenshot_20250611-105507_Firefox~2.png](https://github.com/user-attachments/assets/623c6552-7a8b-451d-bb5b-1a7cccafbd0d)

**Comment by ahobsonsayers** [comment]
Oh this is very interesting you don't see this!

Here is a screenshot from my About Readest on the web. I also tried and Chrome and got the same issue.

I wonder if this is because I am on mobile. I can try on my laptop tonight 

![Screenshot_20250611-105507_Firefox~2.png](https://github.com/user-attachments/assets/623c6552-7a8b-451d-bb5b-1a7cccafbd0d)

**Comment by ahobsonsayers** [comment]
Interestingly, i am also seeing this on my desktop 🤔 

I could probably send a single use link @chrox if that is helpful

![Image](https://github.com/user-attachments/assets/b4d83176-ff44-4768-aa1c-0f74ed8639c8)

**Comment by chrox** [comment]
Please send to readestapp@gmail.com

**Comment by ahobsonsayers** [comment]
Thanks for your help - sent an email

**Comment by chrox** [comment]
> Thanks for your help - sent an email

Thanks. This will be fixed in the next release.
