### ISSUE TITLE
TTS voice list is empty for English for certain book language codes

### ISSUE THREAD

**Issue by StepanSad** [readest/readest#1627]
No voices for English after Update
If you use TTS, it doesn't show the ENG voices. I think it's because of Lang Locales (en-US, en-GB etc.)

> When I'm put wrong Locale name in Ukrainian Voice the same is happening 

<img width="686" height="505" alt="Image" src="https://github.com/user-attachments/assets/428dee16-50ad-4ffb-aef5-22e649104ad5" />

Idk what exactly is happening, but I think that Readest looking for "en" or "en-EN". But there's no such locale.
> Operating System: Android 16 (WebView 137.0)
> Readest Version: 0.9.65
> TTS Engine: MultiTTS (filmora)

**Comment by StepanSad** [comment]
<img width="2559" height="1600" alt="Image" src="https://github.com/user-attachments/assets/ffc0fcbe-42c9-4eb8-abc5-0f5a626d969f" />
<img width="663" height="1557" alt="Image" src="https://github.com/user-attachments/assets/f2aab5c3-302f-4093-a7e0-a146709ea543" />

What happens if I translate from English to English.

**Comment by StepanSad** [comment]
And also it's not a metadata problem because I checked it
<img width="1217" height="1377" alt="Image" src="https://github.com/user-attachments/assets/a1cfc3b7-fe0a-4ba0-9179-a65fc50896eb" />

**Comment by StepanSad** [comment]
<img width="2559" height="1561" alt="Image" src="https://github.com/user-attachments/assets/5e80da0b-9608-4350-902f-9a3b885c806b" />
<img width="2559" height="1561" alt="Image" src="https://github.com/user-attachments/assets/795b1a74-26ef-4486-8d51-7871379b28e0" />
If you manually change to uk-UA then everything works fine. So only the English locale code is buggy.

**Comment by chrox** [comment]
Does your system tts have English voices? Or does it work for English in the last Readest version?

**Comment by StepanSad** [comment]
> Does your system tts have English voices? Or does it work for English in the last Readest version?

Yes, it does. But it's the same. No voices

**Comment by StepanSad** [comment]
> Does your system tts have English voices? Or does it work for English in the last Readest version?

Yes it does. And its working.

<img width="2560" height="1600" alt="Image" src="https://github.com/user-attachments/assets/d448d628-39ef-4ae1-a8b1-d95b20fe3db4" />

<img width="2560" height="1600" alt="Image" src="https://github.com/user-attachments/assets/717f1d80-290e-4e1b-a5e2-ee222e10e93d" />

**Comment by chrox** [comment]
> > Does your system tts have English voices? Or does it work for English in the last Readest version?
> 
> Yes, it does. But it's the same. No voices

Sounds like a locale problem. Could you test if it works when you change your device locale to en-US (might need to change the language to English and region to the US)?

**Comment by chrox** [comment]
> > > Does your system tts have English voices? Or does it work for English in the last Readest version?
> > 
> > 
> > Yes, it does. But it's the same. No voices

Sounds like a locale problem. Could you test if the English voices appears when you change your device locale to en-US (might need to change the language to English and region to the US)?

**Comment by chrox** [comment]
So what's your default locale settings when the English voices do not appear?

**Comment by StepanSad** [comment]
Sorry, I fixed the error in the previous message. The device has the same locale. This is a problem with custom TTS. "TTS server" and "Edge TTS" also don't work because of this.

**Comment by StepanSad** [comment]
> So what's your default locale settings when the English voices do not appear?

This does not depend on the device locale, only on the book locale, where any "en, eng, en-US, En-GB, " will not work.

**Comment by chrox** [comment]
> Sorry, I fixed the error in the previous message. The device has the same locale. This is a problem with custom TTS. "TTS server" and "Edge TTS" also don't work because of this.

> > So what's your default locale settings when the English voices do not appear?
> 
> This does not depend on the device locale, only on the book locale, where any "en, eng, en-US, En-GB, " will not work.

Sorry that I still don’t understand how your solution actually fixed the problem. Could you explain it in more detail? You mean you changed the language code in the book metadata so that English voices can appear in the list?

**Comment by StepanSad** [comment]
> > Sorry, I fixed the error in the previous message. The device has the same locale. This is a problem with custom TTS. "TTS server" and "Edge TTS" also don't work because of this.
> 
> > > So what's your default locale settings when the English voices do not appear?
> > 
> > 
> > This does not depend on the device locale, only on the book locale, where any "en, eng, en-US, En-GB, " will not work.
> 
> Sorry that I still don’t understand how your solution actually fixed the problem. Could you explain it in more detail? You mean you changed the language code in the book metadata so that English voices can appear in the list?

I changed the book's locale to Ukrainian (uk-UA) and the voices appeared. And they probably work because the voices are multi-lingual

**Comment by chrox** [comment]
So if you change the language code in the metadata to any of en, eng, en-US, En-GB, the English voices will disappear, right? This might be a bug.

**Comment by StepanSad** [comment]
> So if you change the language code in the metadata to any of en, eng, en-US, En-GB, the English voices will disappear, right? This might be a bug.

Yes, exactly

**Comment by StepanSad** [comment]
I just wanted to add more details to confirm this.
