### ISSUE TITLE
OPDS downloads fail on ipad

### ISSUE THREAD

**Issue by naveg** [readest/readest#2589]
OPDS catalog can be added and browsed no problem, but downloading books does not work.

<img width="1024" height="1366" alt="Image" src="https://github.com/user-attachments/assets/78c9dc5a-4335-46aa-9dfd-4f7bdb3b1d8f" />

## Technical inputs

Operating System: ipadOS 26.1

Readest Version: 0.9.94

**Comment by chrox** [comment]
Could you try downloading a book from the catalog of the project Gutenberg? If it works it might be a parsing problem to extract the download link. Is your custom OPDS server hosted with calibre? How could I reproduce this problem?

**Comment by naveg** [comment]
Gutenberg works. I am using https://github.com/janeczku/calibre-web as an opds frontend for calibre

**Comment by chrox** [comment]
I will make some tests on that setup.

**Comment by chrox** [comment]
This is fixed in #2592.

**Comment by Tom-Enns** [comment]
This is still failing for me in the exact same way after updating to the latest release. Fails on iOS and MacOS. I too am using Calibre Web Automated OPDS server. Project Gutenberg works fine on both devices.

**Comment by chrox** [comment]
> This is still failing for me in the exact same way after updating to the latest release. Fails on iOS and MacOS. I too am using Calibre Web Automated OPDS server. Project Gutenberg works fine on both devices.

I’ve confirmed it works on Readest 0.9.95 (macOS and iOS) with Calibre 8.10 and Calibre Web 0.6.25. I haven’t tested it with Calibre Web Automated, which may have its own quirks. I’ll look into that later.
