### ISSUE TITLE
FR: Rearrange reader control elements based on the book's reading direction.

### ISSUE THREAD

**Issue by ahmed-0011** [readest/readest#451]
Currently the control elements of the reader are always placed from left to right; however, since there are books that are written with right-to-left languages (e.g., Arabic) or even comic books or CBZ books that are supposed to be read from right to left, then this arrangement doesn't make sense, especially because the reading progress is starting from the left side instead of the right.

Currently the control elements look like this:

![Image](https://github.com/user-attachments/assets/a1de8ce8-5789-40e1-a08f-a6dc99a3bda6)

So, I added the `dir="rtl"` attribute on the container of the control elements, and here is what it should look like if the user is reading an RTL book: ![Image](https://github.com/user-attachments/assets/f6b5c0ac-5d0a-445d-a5c3-51f2ac1fdfa3)

This is not a 100% actual representation of what it should look like because the directions of the icons "Go left" and "Go right" ... etc. are incorrect.

This issue is independent from the RTL language support for the Readest user interface. Because, for example, maybe the user will open an Arabic book while the user interface for Readest is in English.

---

So, I think that Readest should automatically detect the reading direction based on the book metadata (although not all formats have a standard way to define metadata). And also, there should be a switch button that allows the user to alternate between RTL and LTR reading modes.

**Comment by chrox** [comment]
I'm not sure if it's proper to dramatically change the layout like this for different books with different languages. But I think we can make the UI layout to be RTL when the user select the UI language, for example when selecting Arabic or Hebrew. So when the UI language is RTL the layout should be RTL regardless of the book language. What do you think about this?

**Comment by chrox** [comment]
cc @sempijja

**Comment by ahmed-0011** [comment]
> I'm not sure if it's proper to dramatically change the layout like this for different books with different languages. But I think we can make the UI layout to be RTL when the user select the UI language, for example when selecting Arabic or Hebrew. So when the UI language is RTL the layout should be RTL regardless of the book language. What do you think about this?

In RTL books, the pages are not displayed in the same order as LTR languages.

So, when opening an English book, the first page is displayed on the left side and the second is displayed on the right, and so on...

But, for an RTL book (e.g., an Arabic book), it's the other way around; the first page should be displayed on the right side, and the second page is on the left. So, since the user will be reading the book from right to left, it will probably be confusing if the reading progress bar is advancing in the opposite direction (LTR).

Currently, Readest displays Arabic and other RTL books in the wrong way because it displays the first page on the left side.

Regarding your point to set the layout of the reader based on the languages of Readest, I think it won't work, mainly because a person might read Arabic books while preferring to use English as the language of the UI of Readest.

**Comment by chrox** [comment]
Yes. The column order is fine to be changed according to the book language. But I'm not sure if the UI elements like the order of progress bar and navigation buttons as you describe in the screenshots should be changed with the book language or with the UI language. I prefer to change them with UI language.

**Comment by ahmed-0011** [comment]
I think it's inconvenient to have to change Readest's UI language every time you want to read a book with a different reading flow (RTL or LTR). Also, when you set your preferred language for an application UI, you probably intend to use it all the time, and you will get used to it.

I think the reading progress bar is the most important element of all other control elements to make it adjust based on the book's reading direction. Because if not, the bar will advance in the opposite reading direction.

Changing the column order requires also at least changing the direction of the reading progress bar, imo.

**Comment by chrox** [comment]
> I think it's inconvenient to have to change Readest's UI language every time you want to read a book with a different reading flow (RTL or LTR). Also, when you set your preferred language for an application UI, you probably intend to use it all the time, and you will get used to it.
> 
> I think the reading progress bar is the most important element of all other control elements to make it adjust based on the book's reading direction. Because if not, the bar will advance in the opposite reading direction.
> 
> Changing the column order requires also at least changing the direction of the reading progress bar, imo.

I would like to divide the whole interface of the application into the content interface and the user interface. The content interface displays the book content, usually the main text, footnotes, table and graphics in the book. And the user interface shows the controls, buttons, progress bars, text inputs and some other widgets, mainly for user interaction.

There is no doubt that the content interface should be changed to RTL when possible according to the book content. But it will be very strange to change the UI layout to RTL for an English/Chinese UI language like this:

![Image](https://github.com/user-attachments/assets/3b2370e7-2c4b-4cb6-8ba3-9fd183bae47b)

To make things more complicated, Readest can open two or more books at the same time which may sometimes have RTL language and LTR language at the same time. It will be hard to decide the layout of the UI.

**Comment by chrox** [comment]
I'm aware that the progress bar might be a special case for RTL layout. Because it's highly relevant to the content/page layout. For RTL language the left direction is the forward direction. So may be the progress bar or the whole footer bar is a special case of the UI or we classify it to the content interface which is responsive to the content language.

![Image](https://github.com/user-attachments/assets/85bc4d2b-8612-403d-8897-57cbeb426ced)

**Comment by ahmed-0011** [comment]
> There is no doubt that the content interface should be changed to RTL when possible according to the book content. But it will be very strange to change the UI layout to RTL for an English/Chinese UI language like this:
> 
> ![Image](https://github.com/user-attachments/assets/3b2370e7-2c4b-4cb6-8ba3-9fd183bae47b)

Yes, but i was talking in the context of the rendering area where the book is displayed along with the footer bar that cotnains the control elements. So, defentiely the main Readest UI (e.g, the layout & font configuration dialog) shouldn't be affected.

**Comment by chrox** [comment]
@ahmed-0011 I have little experience on RTL writing languages. So if there is other widgets that need to change the direction i.e. the table of contents probably, please let me know.

**Comment by ahmed-0011** [comment]
Yes, the items in the table of contents section should be right-aligned as well, which will make the 3 dots or the ellipses appear on the left side if the text is too long.

I skimmed quickly through the changes in the commit about the direction of the read progress bar; I think it's better to consider using the `dir` HTML attribute instead of the CSS property.

Here's this text quoted from MDN about this topic:

> As the directionality of the text is semantically related to its content and not to its presentation, it is recommended that web developers use this attribute instead of the related CSS properties when possible. That way, the text will display correctly even on a browser that doesn't support CSS or has the CSS deactivated.

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir

**Comment by ahmed-0011** [comment]
So, currently only the reading progress bar changes the progress direction based on the book's reading direction.

I was thinking that the elements in both of these containers should be ordered in the reverse direction if the user opens an RTL book:

\[1\]: 

![Image](https://github.com/user-attachments/assets/0a5e17b9-4412-4cbc-88fd-0f2e7640b29f)

\[2\]: 

![Image](https://github.com/user-attachments/assets/d730d223-f9fb-40c9-928d-d68324e1ccd9)

I think that reversing the direction of the reading progress bar (without changing its order in the container) is mostly sufficient.

Maybe it's better to leave the order of the elements in these containers to be the same, regardless of the book's reading direction.

**Comment by chrox** [comment]
More widgets are supporting RTL direction with #504.

**Comment by ahmed-0011** [comment]
I think it's important that Readest allow the user to switch between RTL or LRT reading modes however they like. So, there should be a button to switch between RTL and LTR... maybe in the kebab menu (three-dotted menu) below the "Scrolled Mode" item or in the Layout & Font configuration dialog?

**Comment by chrox** [comment]
```
const mightBeRTLBook = langCode === 'zh' || langCode === 'ja' || langCode === 'ko' || langCode === '';
```

There is one. But this is only for book languages like CJK that RTL is optional. For other languages RTL or LTR is mandatory and determined and providing options to change it seems unreasonable.

**Comment by ahmed-0011** [comment]
But having this option can be useful because sometimes the metadata about the book's language or the reading direction can be missing. Also, the CBZ format doesn't have a standard way to define metadata, so the user won't be able to change the order of the pages to be from right to left.

**Comment by chrox** [comment]
So if there is no `langCode` it should be `mightBeRTLBook` and the RTL options are shown. If the `langCode` is wrong, I think it might be the user's or the publisher's responsibility to correct it.

**Comment by chrox** [comment]
The philosophy of Readest is "Do not add configurations unless necessary". So we'd better wait for bad cases that current configurations cannot handle then we will see if it's necessary to add the configurations.

**Comment by ahmed-0011** [comment]
Sorry, I just noticed that there is an option to select the reading direction in the Layout & Font dialog when opening a CBZ file.

I thought that there was no such option. :)

**Comment by ahmed-0011** [comment]
Some improvements for the RTL interface:

\[1\]:

![Image](https://github.com/user-attachments/assets/f1a17f06-a847-4ead-9871-347c0dc93978)

The icons for "Go forward" and "Go backward" should be switched. The order of the elements is correct; only the icons are in the opposite direction.

\[2\]:

![Image](https://github.com/user-attachments/assets/d00fb0c1-fcc6-4a98-89e0-22ec8d730cec)

Since the "Delete" button is not related to the content of the book, I think it should stay on the left side since I'm using Readest with English. So, only the content of the annotation should be set to RTL.

\[3\]:

![Image](https://github.com/user-attachments/assets/31fbd03c-678d-4e81-8349-9711b4899bae)

The notebook still doesn't support RTL. But similar to the annotations, the "Delete" and "Edit" buttons shouldn't be set to RTL because they are not related to the content.

**Comment by chrox** [comment]
Fixed in #535.

**Comment by ahmed-0011** [comment]
I tested the latest release (0.9.20). The "Go Forward" and "Go Back" still have some issues.

![Image](https://github.com/user-attachments/assets/aa833caa-7b32-4a65-95a5-8734c9124f2e)

This is how they look in the latest release. Visually they are correct; however, "Go back" should be on the right and "Go Forward" should be on the left. So, only the icons (SVG) should be switched between these two buttons. So, the original order before the latest changes is accurate. Sorry for the misunderstanding.

**Comment by chrox** [comment]
Why "Go back" should be on the right? It's pretty valid to "Go back" to a page in forward direction.

**Comment by ahmed-0011** [comment]
It's more consistent because in the LTR reading flow, the "Go forward" button is also near the reading progress percentage. Additionally, the reading progress bar is advancing towards the left, so it makes sense that "Go Forward" will be on the left and "Go Back" on the right.

**Comment by chrox** [comment]
In the reading direction, no matter in LTR or RTL, it goes "Go Back" and then "Go forward". That's more reasonable and consistent. Will fix it later.
